---
default: &default
  activate_spawns:
    class: "Clock::ActivateSpawnsJob"
    schedule: "every minute"
  expire_spawns:
    class: "Clock::ExpireSpawnsJob"
    schedule: "every minute"
  monsters_attack_characters:
    class: "Clock::MonstersAttackCharactersJob"
    schedule: "every 5 seconds"
  regenerate_health:
    class: "Clock::RegenerateHealthJob"
    schedule: "every 30 seconds"
  sign_out_inactive_characters:
    class: "Clock::SignOutInactiveCharactersJob"
    schedule: "every minute"

development:
  <<: *default

production:
  <<: *default
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
